### ISSUE TITLE
there is no recipe for the tnt table

### ISSUE THREAD

**Issue by peanutinky** [Logboy2000/Demolitionist-Villager-Mod#1]
there is no recipe for the tnt table to have the villager to take a job. the recipe in your mod is blank that is why there is no table or villager please fix

**Comment by Logboy2000** [comment]
I'm so sorry i've had quite a bit of school as of recent so I am now updating to 1.20.2 as well as fixeing all of the bugs (:

**Comment by Logboy2000** [comment]
All issues fixed!

Changelog:
1.20.2 Support
Fixed missing block texture
Fixed missing loot table
Fixed missing recipe

Check it out:
https://modrinth.com/mod/demolitionist-villager
